"""add_platform_fee_models

Revision ID: 0c6aa91a55ea
Revises: b0dfd279c5fe
Create Date: 2026-06-10 06:54:33.683832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6aa91a55ea'
down_revision: Union[str, None] = 'b0dfd279c5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'platform_fee_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('escrow_release_fee_enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('escrow_release_fee_type', sa.String(), nullable=False, server_default='percentage'),
        sa.Column('escrow_release_fee_value', sa.Float(), nullable=False, server_default='5.0'),
        sa.Column('deposit_fee_enabled', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('deposit_fee_type', sa.String(), nullable=False, server_default='percentage'),
        sa.Column('deposit_fee_value', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('withdrawal_fee_enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('withdrawal_fee_type', sa.String(), nullable=False, server_default='percentage'),
        sa.Column('withdrawal_fee_value', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_by_admin_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['updated_by_admin_id'], ['superadmin.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'platform_revenue_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('gross_amount_cents', sa.BigInteger(), nullable=False),
        sa.Column('fee_amount_cents', sa.BigInteger(), nullable=False),
        sa.Column('fee_type', sa.String(), nullable=False),
        sa.Column('fee_value', sa.Float(), nullable=False),
        sa.Column('reference', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('support_ticket_replies_ticket_id_fkey', 'support_ticket_replies', type_='foreignkey')
    op.create_foreign_key(None, 'support_ticket_replies', 'support_tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_ticket_replies', type_='foreignkey')
    op.create_foreign_key('support_ticket_replies_ticket_id_fkey', 'support_ticket_replies', 'support_tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_table('platform_revenue_logs')
    op.drop_table('platform_fee_config')
    # ### end Alembic commands ###
