"""Adding avatar to user table

Revision ID: 25416e912c15
Revises: 260b77f76526
Create Date: 2025-10-05 14:47:28.525334

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25416e912c15'
down_revision: Union[str, None] = '260b77f76526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('superadmin', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('superadmin', 'avatar')
    # ### end Alembic commands ###
