"""Adding price to services

Revision ID: 260b77f76526
Revises: ac542ed08c10
Create Date: 2025-10-05 14:17:39.598079

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '260b77f76526'
down_revision: Union[str, None] = 'ac542ed08c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('discount', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('mfa', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('users', sa.Column('mfa_code', sqlmodel.sql.sqltypes.AutoString(), server_default='null', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_code')
    op.drop_column('users', 'mfa')
    op.drop_column('services', 'discount_percent')
    op.drop_column('services', 'discount')
    op.drop_column('services', 'price')
    # ### end Alembic commands ###
