"""ading value to kyc entries

Revision ID: 3940ece90f16
Revises: 56c17be756f6
Create Date: 2025-12-06 16:36:52.547788

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3940ece90f16'
down_revision: Union[str, None] = '56c17be756f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc', sa.Column('id_document_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc', 'id_document_value')
    # ### end Alembic commands ###
