"""add driver vehicles table

Revision ID: 3d766d667485
Revises: 0c6aa91a55ea
Create Date: 2026-06-30 19:25:50.256310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d766d667485'
down_revision: Union[str, None] = '0c6aa91a55ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_vehicles',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('driver_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('vehicle_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_vehicles_driver_id'), 'driver_vehicles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_vehicles_id'), 'driver_vehicles', ['id'], unique=False)
    op.add_column('driver_profiles', sa.Column('vehicle_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE driver_profiles SET vehicle_type = 'car' WHERE vehicle_type IS NULL")
    op.alter_column('driver_profiles', 'vehicle_type', nullable=False)

    op.drop_constraint(op.f('support_ticket_replies_ticket_id_fkey'), 'support_ticket_replies', type_='foreignkey')
    op.create_foreign_key(None, 'support_ticket_replies', 'support_tickets', ['ticket_id'], ['id'])

    op.add_column('trips', sa.Column('vehicle_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE trips SET vehicle_type = 'car' WHERE vehicle_type IS NULL")
    op.alter_column('trips', 'vehicle_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'vehicle_type')
    op.drop_constraint(None, 'support_ticket_replies', type_='foreignkey')
    op.create_foreign_key(op.f('support_ticket_replies_ticket_id_fkey'), 'support_ticket_replies', 'support_tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_column('driver_profiles', 'vehicle_type')
    op.drop_index(op.f('ix_driver_vehicles_id'), table_name='driver_vehicles')
    op.drop_index(op.f('ix_driver_vehicles_driver_id'), table_name='driver_vehicles')
    op.drop_table('driver_vehicles')
    # ### end Alembic commands ###
