"""Adding relationship to work submission

Revision ID: 597a45aac5bf
Revises: 25416e912c15
Create Date: 2025-10-22 00:02:33.934198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '597a45aac5bf'
down_revision: Union[str, None] = '25416e912c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profiles_team_id', table_name='profiles')
    op.drop_index('ix_profiles_user_id', table_name='profiles')
    op.drop_table('profiles')
    op.add_column('work_submissions', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_work_submissions_user_id'), 'work_submissions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'work_submissions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_submissions', type_='foreignkey')
    op.drop_index(op.f('ix_work_submissions_user_id'), table_name='work_submissions')
    op.drop_column('work_submissions', 'user_id')
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey')
    )
    op.create_index('ix_profiles_user_id', 'profiles', ['user_id'], unique=True)
    op.create_index('ix_profiles_team_id', 'profiles', ['team_id'], unique=False)
    # ### end Alembic commands ###
