"""fixing time in escrow and riding

Revision ID: 76025a38eaa0
Revises: a66c9cf4f6c7
Create Date: 2025-12-23 06:53:06.696256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76025a38eaa0'
down_revision: Union[str, None] = 'a66c9cf4f6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rides_driver_id', table_name='rides')
    op.drop_index('ix_rides_user_id', table_name='rides')
    op.drop_table('rides')
    op.drop_index('ix_driver_profiles_id', table_name='driver_profiles')
    op.drop_index('ix_driver_profiles_user_id', table_name='driver_profiles')
    op.add_column('escrow', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('escrow', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escrow', 'updated_at')
    op.drop_column('escrow', 'created_at')
    op.create_table('driver_locations',
    sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], name='driver_locations_driver_id_fkey'),
    sa.PrimaryKeyConstraint('driver_id', name='driver_locations_pkey')
    )
    op.create_table('driver_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('car_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('car_model', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('plate_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('successful_rides', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_rides', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_rides', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rank', postgresql.ENUM('STARTER', 'EXPERIENCED', 'EXPERT', 'LEGEND', name='driverrank'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PENDING', 'SUSPENDED', 'BANNED', name='driverstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='driver_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='driver_profiles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_driver_profiles_user_id', 'driver_profiles', ['user_id'], unique=True)
    op.create_index('ix_driver_profiles_id', 'driver_profiles', ['id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('STARTED', 'COMPLETED', 'FAILED', 'CANCELLED', name='ridestatus'), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('earnings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], name='rides_driver_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rides_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rides_pkey')
    )
    op.create_index('ix_rides_user_id', 'rides', ['user_id'], unique=False)
    op.create_index('ix_rides_driver_id', 'rides', ['driver_id'], unique=False)
    # ### end Alembic commands ###
