"""adding plate number

Revision ID: a66c9cf4f6c7
Revises: f82ad1cbc730
Create Date: 2025-12-22 11:46:08.990885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a66c9cf4f6c7'
down_revision: Union[str, None] = 'f82ad1cbc730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_driver_profiles_id', table_name='driver_profiles')
    op.drop_index('ix_driver_profiles_user_id', table_name='driver_profiles')
    op.drop_table('driver_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('car_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('car_model', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('successful_rides', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_rides', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_rides', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rank', postgresql.ENUM('STARTER', 'EXPERIENCED', 'EXPERT', 'LEGEND', name='driverrank'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PENDING', 'SUSPENDED', 'BANNED', name='driverstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='driver_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='driver_profiles_pkey')
    )
    op.create_index('ix_driver_profiles_user_id', 'driver_profiles', ['user_id'], unique=True)
    op.create_index('ix_driver_profiles_id', 'driver_profiles', ['id'], unique=False)
    # ### end Alembic commands ###
