"""Add monnify payment models

Revision ID: b0dfd279c5fe
Revises: e6a0809d47fe
Create Date: 2026-05-16 16:42:21.120978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b0dfd279c5fe'
down_revision: Union[str, None] = 'e6a0809d47fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bank_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('bank_code', sa.String(length=10), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bank_accounts_id'), 'user_bank_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_user_bank_accounts_user_id'), 'user_bank_accounts', ['user_id'], unique=False)
    op.create_table('admin_payment_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_approve_withdrawals', sa.Boolean(), nullable=False),
    sa.Column('screen_deposits', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_admin_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['superadmin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monnify_reference', sa.String(), nullable=True),
    sa.Column('monnify_transaction_ref', sa.String(), nullable=True),
    sa.Column('payment_link', sa.String(), nullable=True),
    sa.Column('virtual_account_number', sa.String(), nullable=True),
    sa.Column('virtual_bank_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'screened_pending', 'approved', 'failed', 'expired', name='deposit_status_enum'), nullable=False),
    sa.Column('approved_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_admin_id'], ['superadmin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_requests_id'), 'deposit_requests', ['id'], unique=False)
    op.create_index(op.f('ix_deposit_requests_monnify_reference'), 'deposit_requests', ['monnify_reference'], unique=False)
    op.create_index(op.f('ix_deposit_requests_monnify_transaction_ref'), 'deposit_requests', ['monnify_transaction_ref'], unique=False)
    op.create_index(op.f('ix_deposit_requests_status'), 'deposit_requests', ['status'], unique=False)
    op.create_index(op.f('ix_deposit_requests_user_id'), 'deposit_requests', ['user_id'], unique=False)
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monnify_reference', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'processing', 'completed', 'rejected', 'failed', name='withdrawal_status_enum'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approved_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_admin_id'], ['superadmin.id'], ),
    sa.ForeignKeyConstraint(['bank_account_id'], ['user_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_requests_id'), 'withdrawal_requests', ['id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_monnify_reference'), 'withdrawal_requests', ['monnify_reference'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_status'), 'withdrawal_requests', ['status'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_user_id'), 'withdrawal_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawal_requests_user_id'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_status'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_monnify_reference'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_id'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_index(op.f('ix_deposit_requests_user_id'), table_name='deposit_requests')
    op.drop_index(op.f('ix_deposit_requests_status'), table_name='deposit_requests')
    op.drop_index(op.f('ix_deposit_requests_monnify_transaction_ref'), table_name='deposit_requests')
    op.drop_index(op.f('ix_deposit_requests_monnify_reference'), table_name='deposit_requests')
    op.drop_index(op.f('ix_deposit_requests_id'), table_name='deposit_requests')
    op.drop_table('deposit_requests')
    op.drop_table('admin_payment_settings')
    op.drop_index(op.f('ix_user_bank_accounts_user_id'), table_name='user_bank_accounts')
    op.drop_index(op.f('ix_user_bank_accounts_id'), table_name='user_bank_accounts')
    op.drop_table('user_bank_accounts')
    # ### end Alembic commands ###
