"""fixing duplicte entrires

Revision ID: cac88c13b9c8
Revises: 5ee050698a44
Create Date: 2025-10-22 08:14:18.956365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac88c13b9c8'
down_revision: Union[str, None] = '5ee050698a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_submissions_escrow_id', table_name='work_submissions')
    op.create_index(op.f('ix_work_submissions_escrow_id'), 'work_submissions', ['escrow_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_submissions_escrow_id'), table_name='work_submissions')
    op.create_index('ix_work_submissions_escrow_id', 'work_submissions', ['escrow_id'], unique=False)
    # ### end Alembic commands ###
