"""Add PostedJob model

Revision ID: e6a0809d47fe
Revises: 76025a38eaa0
Create Date: 2026-05-13 05:32:43.941356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6a0809d47fe'
down_revision: Union[str, None] = '76025a38eaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_locations', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_driver_profiles_id'), 'driver_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_driver_profiles_user_id'), 'driver_profiles', ['user_id'], unique=True)
    op.alter_column('escrow', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('escrow', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_unique_constraint(None, 'posted_jobs', ['id'])
    op.add_column('price_negotiations', sa.Column('posted_job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_price_negotiations_posted_job_id'), 'price_negotiations', ['posted_job_id'], unique=False)
    op.create_foreign_key(None, 'price_negotiations', 'posted_jobs', ['posted_job_id'], ['id'])
    op.alter_column('roles', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'DEACTIVATED', name='rolestatus'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'::rolestatus"))
    op.create_index(op.f('ix_support_ticket_replies_author_admin_id'), 'support_ticket_replies', ['author_admin_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_assigned_admin_id'), 'support_tickets', ['assigned_admin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_assigned_admin_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_ticket_replies_author_admin_id'), table_name='support_ticket_replies')
    op.alter_column('roles', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'DEACTIVATED', name='rolestatus'),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'::rolestatus"))
    op.drop_constraint(None, 'price_negotiations', type_='foreignkey')
    op.drop_index(op.f('ix_price_negotiations_posted_job_id'), table_name='price_negotiations')
    op.drop_column('price_negotiations', 'posted_job_id')
    op.drop_constraint(None, 'posted_jobs', type_='unique')
    op.alter_column('escrow', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('escrow', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_driver_profiles_user_id'), table_name='driver_profiles')
    op.drop_index(op.f('ix_driver_profiles_id'), table_name='driver_profiles')
    op.alter_column('driver_locations', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
