"""making user unique in portfolio

Revision ID: f82ad1cbc730
Revises: fa8ba665d169
Create Date: 2025-12-11 09:54:35.638899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82ad1cbc730'
down_revision: Union[str, None] = 'fa8ba665d169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_portfolio_user_id', table_name='user_portfolio')
    op.create_index(op.f('ix_user_portfolio_user_id'), 'user_portfolio', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_portfolio_user_id'), table_name='user_portfolio')
    op.create_index('ix_user_portfolio_user_id', 'user_portfolio', ['user_id'], unique=False)
    # ### end Alembic commands ###
