"""adiing filed to portfolio tables

Revision ID: fa8ba665d169
Revises: 3940ece90f16
Create Date: 2025-12-10 22:48:05.344253

"""
from typing import Sequence, Union

import sqlmodel
from sqlmodel import SQLModel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8ba665d169'
down_revision: Union[str, None] = '3940ece90f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_portfolio', sa.Column('facebook', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_portfolio', sa.Column('twitter', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_portfolio', sa.Column('youtube', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_portfolio', sa.Column('instagram', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_portfolio', sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_portfolio_facebook'), 'user_portfolio', ['facebook'], unique=True)
    op.create_index(op.f('ix_user_portfolio_instagram'), 'user_portfolio', ['instagram'], unique=True)
    op.create_index(op.f('ix_user_portfolio_twitter'), 'user_portfolio', ['twitter'], unique=True)
    op.create_index(op.f('ix_user_portfolio_website'), 'user_portfolio', ['website'], unique=True)
    op.create_index(op.f('ix_user_portfolio_youtube'), 'user_portfolio', ['youtube'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_portfolio_youtube'), table_name='user_portfolio')
    op.drop_index(op.f('ix_user_portfolio_website'), table_name='user_portfolio')
    op.drop_index(op.f('ix_user_portfolio_twitter'), table_name='user_portfolio')
    op.drop_index(op.f('ix_user_portfolio_instagram'), table_name='user_portfolio')
    op.drop_index(op.f('ix_user_portfolio_facebook'), table_name='user_portfolio')
    op.drop_column('user_portfolio', 'website')
    op.drop_column('user_portfolio', 'instagram')
    op.drop_column('user_portfolio', 'youtube')
    op.drop_column('user_portfolio', 'twitter')
    op.drop_column('user_portfolio', 'facebook')
    # ### end Alembic commands ###
